"""update the migration

Revision ID: 2970be2f45fc
Revises: 9eaa6dd1946b
Create Date: 2025-04-02 17:13:33.371328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2970be2f45fc'
down_revision: Union[str, None] = '9eaa6dd1946b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('borrow_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column('users', 'age',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Integer(),
                   existing_nullable=False,
                   postgresql_using="age::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    op.drop_table('borrows')
    # ### end Alembic commands ###
